[package]
name = "eosim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
fxhash = "0.2.1"
indexmap = "2.2.6"
rand = "0.8.5"
